### ISSUE TITLE
map data trace

### ISSUE THREAD

**Issue by luojh2015** [ohko/logger#1]
https://github.com/ohko/logger/blob/157b51a0d33fa6cd216759df551576e71f45041a/logger.go#L70

storePrefix[level]直接调用有线程竞争问题，updatePrefix上了锁，read无锁

**Comment by luojh2015** [comment]
fatal error: concurrent map read and map write

**Comment by luojh2015** [comment]
lock   sync.RWMutex

**Comment by luojh2015** [comment]
func (o *Logger) LogCalldepth(calldepth int, level int, msg ...interface{}) {
	prefix := func() string {
		o.lock.RLock()
		defer o.lock.RUnlock()
		if level < *o.level || *o.level == LoggerLevel5Off {
			return ""
		}

		if level > LoggerLevelNormal {
			level = LoggerLevelNormal
		}

		return o.storePrefix[level]
	}()

	if prefix != "" {
		o.l.Output(calldepth, prefix+fmt.Sprint(msg...))
	}
}

**Comment by luojh2015** [comment]
func (o *Logger) SetLevel(level int) {
	o.lock.Lock()
	defer o.lock.Unlock()
	*o.level = level
}

**Comment by luojh2015** [comment]
func (o *Logger) SetLevel(level int) {
	o.lock.Lock()
	defer o.lock.Unlock()
	*o.level = level
}

**Comment by ohko** [comment]
done https://github.com/ohko/logger/commit/43dfe963d943da00a0dc3038d2ec8c615621c8c8
